// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

public interface ExecuteCodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.ExecuteCodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rplugininterop.CommandOutput output = 1;</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <code>.rplugininterop.CommandOutput output = 1;</code>
   * @return The output.
   */
  com.intellij.r.psi.rinterop.CommandOutput getOutput();
  /**
   * <code>.rplugininterop.CommandOutput output = 1;</code>
   */
  com.intellij.r.psi.rinterop.CommandOutputOrBuilder getOutputOrBuilder();

  /**
   * <code>string exception = 2;</code>
   * @return Whether the exception field is set.
   */
  boolean hasException();
  /**
   * <code>string exception = 2;</code>
   * @return The exception.
   */
  java.lang.String getException();
  /**
   * <code>string exception = 2;</code>
   * @return The bytes for exception.
   */
  com.google.protobuf.ByteString
      getExceptionBytes();

  com.intellij.r.psi.rinterop.ExecuteCodeResponse.MsgCase getMsgCase();
}
