// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

public interface GetInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.GetInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rVersion = 1;</code>
   * @return The rVersion.
   */
  java.lang.String getRVersion();
  /**
   * <code>string rVersion = 1;</code>
   * @return The bytes for rVersion.
   */
  com.google.protobuf.ByteString
      getRVersionBytes();

  /**
   * <code>int32 pid = 2;</code>
   * @return The pid.
   */
  int getPid();
}
