// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

/**
 * Protobuf type {@code rplugininterop.GetVariablesRequest}
 */
public final class GetVariablesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.GetVariablesRequest)
    GetVariablesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVariablesRequest.newBuilder() to construct.
  private GetVariablesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVariablesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetVariablesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GetVariablesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GetVariablesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellij.r.psi.rinterop.GetVariablesRequest.class, com.intellij.r.psi.rinterop.GetVariablesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int OBJ_FIELD_NUMBER = 1;
  private com.intellij.r.psi.rinterop.RRef obj_;
  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   * @return Whether the obj field is set.
   */
  @java.lang.Override
  public boolean hasObj() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   * @return The obj.
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.RRef getObj() {
    return obj_ == null ? com.intellij.r.psi.rinterop.RRef.getDefaultInstance() : obj_;
  }
  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.RRefOrBuilder getObjOrBuilder() {
    return obj_ == null ? com.intellij.r.psi.rinterop.RRef.getDefaultInstance() : obj_;
  }

  public static final int START_FIELD_NUMBER = 2;
  private long start_ = 0L;
  /**
   * <code>int64 start = 2;</code>
   * @return The start.
   */
  @java.lang.Override
  public long getStart() {
    return start_;
  }

  public static final int END_FIELD_NUMBER = 3;
  private long end_ = 0L;
  /**
   * <code>int64 end = 3;</code>
   * @return The end.
   */
  @java.lang.Override
  public long getEnd() {
    return end_;
  }

  public static final int NOHIDDEN_FIELD_NUMBER = 4;
  private boolean noHidden_ = false;
  /**
   * <pre>
   * These parameters are for environments only
   * </pre>
   *
   * <code>bool noHidden = 4;</code>
   * @return The noHidden.
   */
  @java.lang.Override
  public boolean getNoHidden() {
    return noHidden_;
  }

  public static final int NOFUNCTIONS_FIELD_NUMBER = 5;
  private boolean noFunctions_ = false;
  /**
   * <code>bool noFunctions = 5;</code>
   * @return The noFunctions.
   */
  @java.lang.Override
  public boolean getNoFunctions() {
    return noFunctions_;
  }

  public static final int ONLYFUNCTIONS_FIELD_NUMBER = 6;
  private boolean onlyFunctions_ = false;
  /**
   * <code>bool onlyFunctions = 6;</code>
   * @return The onlyFunctions.
   */
  @java.lang.Override
  public boolean getOnlyFunctions() {
    return onlyFunctions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getObj());
    }
    if (start_ != 0L) {
      output.writeInt64(2, start_);
    }
    if (end_ != 0L) {
      output.writeInt64(3, end_);
    }
    if (noHidden_ != false) {
      output.writeBool(4, noHidden_);
    }
    if (noFunctions_ != false) {
      output.writeBool(5, noFunctions_);
    }
    if (onlyFunctions_ != false) {
      output.writeBool(6, onlyFunctions_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getObj());
    }
    if (start_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, start_);
    }
    if (end_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, end_);
    }
    if (noHidden_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, noHidden_);
    }
    if (noFunctions_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, noFunctions_);
    }
    if (onlyFunctions_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, onlyFunctions_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellij.r.psi.rinterop.GetVariablesRequest)) {
      return super.equals(obj);
    }
    com.intellij.r.psi.rinterop.GetVariablesRequest other = (com.intellij.r.psi.rinterop.GetVariablesRequest) obj;

    if (hasObj() != other.hasObj()) return false;
    if (hasObj()) {
      if (!getObj()
          .equals(other.getObj())) return false;
    }
    if (getStart()
        != other.getStart()) return false;
    if (getEnd()
        != other.getEnd()) return false;
    if (getNoHidden()
        != other.getNoHidden()) return false;
    if (getNoFunctions()
        != other.getNoFunctions()) return false;
    if (getOnlyFunctions()
        != other.getOnlyFunctions()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasObj()) {
      hash = (37 * hash) + OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getObj().hashCode();
    }
    hash = (37 * hash) + START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStart());
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEnd());
    hash = (37 * hash) + NOHIDDEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoHidden());
    hash = (37 * hash) + NOFUNCTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoFunctions());
    hash = (37 * hash) + ONLYFUNCTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOnlyFunctions());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.GetVariablesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellij.r.psi.rinterop.GetVariablesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.GetVariablesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.GetVariablesRequest)
      com.intellij.r.psi.rinterop.GetVariablesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GetVariablesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GetVariablesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellij.r.psi.rinterop.GetVariablesRequest.class, com.intellij.r.psi.rinterop.GetVariablesRequest.Builder.class);
    }

    // Construct using com.intellij.r.psi.rinterop.GetVariablesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getObjFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      obj_ = null;
      if (objBuilder_ != null) {
        objBuilder_.dispose();
        objBuilder_ = null;
      }
      start_ = 0L;
      end_ = 0L;
      noHidden_ = false;
      noFunctions_ = false;
      onlyFunctions_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GetVariablesRequest_descriptor;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GetVariablesRequest getDefaultInstanceForType() {
      return com.intellij.r.psi.rinterop.GetVariablesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GetVariablesRequest build() {
      com.intellij.r.psi.rinterop.GetVariablesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GetVariablesRequest buildPartial() {
      com.intellij.r.psi.rinterop.GetVariablesRequest result = new com.intellij.r.psi.rinterop.GetVariablesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.intellij.r.psi.rinterop.GetVariablesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.obj_ = objBuilder_ == null
            ? obj_
            : objBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.start_ = start_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.end_ = end_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.noHidden_ = noHidden_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.noFunctions_ = noFunctions_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.onlyFunctions_ = onlyFunctions_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellij.r.psi.rinterop.GetVariablesRequest) {
        return mergeFrom((com.intellij.r.psi.rinterop.GetVariablesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellij.r.psi.rinterop.GetVariablesRequest other) {
      if (other == com.intellij.r.psi.rinterop.GetVariablesRequest.getDefaultInstance()) return this;
      if (other.hasObj()) {
        mergeObj(other.getObj());
      }
      if (other.getStart() != 0L) {
        setStart(other.getStart());
      }
      if (other.getEnd() != 0L) {
        setEnd(other.getEnd());
      }
      if (other.getNoHidden() != false) {
        setNoHidden(other.getNoHidden());
      }
      if (other.getNoFunctions() != false) {
        setNoFunctions(other.getNoFunctions());
      }
      if (other.getOnlyFunctions() != false) {
        setOnlyFunctions(other.getOnlyFunctions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getObjFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              start_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              end_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              noHidden_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              noFunctions_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              onlyFunctions_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.intellij.r.psi.rinterop.RRef obj_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellij.r.psi.rinterop.RRef, com.intellij.r.psi.rinterop.RRef.Builder, com.intellij.r.psi.rinterop.RRefOrBuilder> objBuilder_;
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     * @return Whether the obj field is set.
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     * @return The obj.
     */
    public com.intellij.r.psi.rinterop.RRef getObj() {
      if (objBuilder_ == null) {
        return obj_ == null ? com.intellij.r.psi.rinterop.RRef.getDefaultInstance() : obj_;
      } else {
        return objBuilder_.getMessage();
      }
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public Builder setObj(com.intellij.r.psi.rinterop.RRef value) {
      if (objBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        obj_ = value;
      } else {
        objBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public Builder setObj(
        com.intellij.r.psi.rinterop.RRef.Builder builderForValue) {
      if (objBuilder_ == null) {
        obj_ = builderForValue.build();
      } else {
        objBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public Builder mergeObj(com.intellij.r.psi.rinterop.RRef value) {
      if (objBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          obj_ != null &&
          obj_ != com.intellij.r.psi.rinterop.RRef.getDefaultInstance()) {
          getObjBuilder().mergeFrom(value);
        } else {
          obj_ = value;
        }
      } else {
        objBuilder_.mergeFrom(value);
      }
      if (obj_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public Builder clearObj() {
      bitField0_ = (bitField0_ & ~0x00000001);
      obj_ = null;
      if (objBuilder_ != null) {
        objBuilder_.dispose();
        objBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public com.intellij.r.psi.rinterop.RRef.Builder getObjBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getObjFieldBuilder().getBuilder();
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    public com.intellij.r.psi.rinterop.RRefOrBuilder getObjOrBuilder() {
      if (objBuilder_ != null) {
        return objBuilder_.getMessageOrBuilder();
      } else {
        return obj_ == null ?
            com.intellij.r.psi.rinterop.RRef.getDefaultInstance() : obj_;
      }
    }
    /**
     * <code>.rplugininterop.RRef obj = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellij.r.psi.rinterop.RRef, com.intellij.r.psi.rinterop.RRef.Builder, com.intellij.r.psi.rinterop.RRefOrBuilder> 
        getObjFieldBuilder() {
      if (objBuilder_ == null) {
        objBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellij.r.psi.rinterop.RRef, com.intellij.r.psi.rinterop.RRef.Builder, com.intellij.r.psi.rinterop.RRefOrBuilder>(
                getObj(),
                getParentForChildren(),
                isClean());
        obj_ = null;
      }
      return objBuilder_;
    }

    private long start_ ;
    /**
     * <code>int64 start = 2;</code>
     * @return The start.
     */
    @java.lang.Override
    public long getStart() {
      return start_;
    }
    /**
     * <code>int64 start = 2;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(long value) {

      start_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000002);
      start_ = 0L;
      onChanged();
      return this;
    }

    private long end_ ;
    /**
     * <code>int64 end = 3;</code>
     * @return The end.
     */
    @java.lang.Override
    public long getEnd() {
      return end_;
    }
    /**
     * <code>int64 end = 3;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(long value) {

      end_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      bitField0_ = (bitField0_ & ~0x00000004);
      end_ = 0L;
      onChanged();
      return this;
    }

    private boolean noHidden_ ;
    /**
     * <pre>
     * These parameters are for environments only
     * </pre>
     *
     * <code>bool noHidden = 4;</code>
     * @return The noHidden.
     */
    @java.lang.Override
    public boolean getNoHidden() {
      return noHidden_;
    }
    /**
     * <pre>
     * These parameters are for environments only
     * </pre>
     *
     * <code>bool noHidden = 4;</code>
     * @param value The noHidden to set.
     * @return This builder for chaining.
     */
    public Builder setNoHidden(boolean value) {

      noHidden_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * These parameters are for environments only
     * </pre>
     *
     * <code>bool noHidden = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoHidden() {
      bitField0_ = (bitField0_ & ~0x00000008);
      noHidden_ = false;
      onChanged();
      return this;
    }

    private boolean noFunctions_ ;
    /**
     * <code>bool noFunctions = 5;</code>
     * @return The noFunctions.
     */
    @java.lang.Override
    public boolean getNoFunctions() {
      return noFunctions_;
    }
    /**
     * <code>bool noFunctions = 5;</code>
     * @param value The noFunctions to set.
     * @return This builder for chaining.
     */
    public Builder setNoFunctions(boolean value) {

      noFunctions_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool noFunctions = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoFunctions() {
      bitField0_ = (bitField0_ & ~0x00000010);
      noFunctions_ = false;
      onChanged();
      return this;
    }

    private boolean onlyFunctions_ ;
    /**
     * <code>bool onlyFunctions = 6;</code>
     * @return The onlyFunctions.
     */
    @java.lang.Override
    public boolean getOnlyFunctions() {
      return onlyFunctions_;
    }
    /**
     * <code>bool onlyFunctions = 6;</code>
     * @param value The onlyFunctions to set.
     * @return This builder for chaining.
     */
    public Builder setOnlyFunctions(boolean value) {

      onlyFunctions_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool onlyFunctions = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlyFunctions() {
      bitField0_ = (bitField0_ & ~0x00000020);
      onlyFunctions_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.GetVariablesRequest)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.GetVariablesRequest)
  private static final com.intellij.r.psi.rinterop.GetVariablesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellij.r.psi.rinterop.GetVariablesRequest();
  }

  public static com.intellij.r.psi.rinterop.GetVariablesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVariablesRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetVariablesRequest>() {
    @java.lang.Override
    public GetVariablesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetVariablesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVariablesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellij.r.psi.rinterop.GetVariablesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

