// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

/**
 * Protobuf type {@code rplugininterop.GraphicsRescaleRequest}
 */
public final class GraphicsRescaleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.GraphicsRescaleRequest)
    GraphicsRescaleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GraphicsRescaleRequest.newBuilder() to construct.
  private GraphicsRescaleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GraphicsRescaleRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GraphicsRescaleRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GraphicsRescaleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GraphicsRescaleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellij.r.psi.rinterop.GraphicsRescaleRequest.class, com.intellij.r.psi.rinterop.GraphicsRescaleRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SNAPSHOTNUMBER_FIELD_NUMBER = 1;
  private int snapshotNumber_ = 0;
  /**
   * <code>int32 snapshotNumber = 1;</code>
   * @return The snapshotNumber.
   */
  @java.lang.Override
  public int getSnapshotNumber() {
    return snapshotNumber_;
  }

  public static final int NEWPARAMETERS_FIELD_NUMBER = 2;
  private com.intellij.r.psi.rinterop.ScreenParameters newParameters_;
  /**
   * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
   * @return Whether the newParameters field is set.
   */
  @java.lang.Override
  public boolean hasNewParameters() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
   * @return The newParameters.
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.ScreenParameters getNewParameters() {
    return newParameters_ == null ? com.intellij.r.psi.rinterop.ScreenParameters.getDefaultInstance() : newParameters_;
  }
  /**
   * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.ScreenParametersOrBuilder getNewParametersOrBuilder() {
    return newParameters_ == null ? com.intellij.r.psi.rinterop.ScreenParameters.getDefaultInstance() : newParameters_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (snapshotNumber_ != 0) {
      output.writeInt32(1, snapshotNumber_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getNewParameters());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (snapshotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, snapshotNumber_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNewParameters());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellij.r.psi.rinterop.GraphicsRescaleRequest)) {
      return super.equals(obj);
    }
    com.intellij.r.psi.rinterop.GraphicsRescaleRequest other = (com.intellij.r.psi.rinterop.GraphicsRescaleRequest) obj;

    if (getSnapshotNumber()
        != other.getSnapshotNumber()) return false;
    if (hasNewParameters() != other.hasNewParameters()) return false;
    if (hasNewParameters()) {
      if (!getNewParameters()
          .equals(other.getNewParameters())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SNAPSHOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSnapshotNumber();
    if (hasNewParameters()) {
      hash = (37 * hash) + NEWPARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getNewParameters().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellij.r.psi.rinterop.GraphicsRescaleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.GraphicsRescaleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.GraphicsRescaleRequest)
      com.intellij.r.psi.rinterop.GraphicsRescaleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GraphicsRescaleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GraphicsRescaleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellij.r.psi.rinterop.GraphicsRescaleRequest.class, com.intellij.r.psi.rinterop.GraphicsRescaleRequest.Builder.class);
    }

    // Construct using com.intellij.r.psi.rinterop.GraphicsRescaleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNewParametersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      snapshotNumber_ = 0;
      newParameters_ = null;
      if (newParametersBuilder_ != null) {
        newParametersBuilder_.dispose();
        newParametersBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_GraphicsRescaleRequest_descriptor;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GraphicsRescaleRequest getDefaultInstanceForType() {
      return com.intellij.r.psi.rinterop.GraphicsRescaleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GraphicsRescaleRequest build() {
      com.intellij.r.psi.rinterop.GraphicsRescaleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.GraphicsRescaleRequest buildPartial() {
      com.intellij.r.psi.rinterop.GraphicsRescaleRequest result = new com.intellij.r.psi.rinterop.GraphicsRescaleRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.intellij.r.psi.rinterop.GraphicsRescaleRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.snapshotNumber_ = snapshotNumber_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.newParameters_ = newParametersBuilder_ == null
            ? newParameters_
            : newParametersBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellij.r.psi.rinterop.GraphicsRescaleRequest) {
        return mergeFrom((com.intellij.r.psi.rinterop.GraphicsRescaleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellij.r.psi.rinterop.GraphicsRescaleRequest other) {
      if (other == com.intellij.r.psi.rinterop.GraphicsRescaleRequest.getDefaultInstance()) return this;
      if (other.getSnapshotNumber() != 0) {
        setSnapshotNumber(other.getSnapshotNumber());
      }
      if (other.hasNewParameters()) {
        mergeNewParameters(other.getNewParameters());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              snapshotNumber_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getNewParametersFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int snapshotNumber_ ;
    /**
     * <code>int32 snapshotNumber = 1;</code>
     * @return The snapshotNumber.
     */
    @java.lang.Override
    public int getSnapshotNumber() {
      return snapshotNumber_;
    }
    /**
     * <code>int32 snapshotNumber = 1;</code>
     * @param value The snapshotNumber to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshotNumber(int value) {

      snapshotNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 snapshotNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapshotNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      snapshotNumber_ = 0;
      onChanged();
      return this;
    }

    private com.intellij.r.psi.rinterop.ScreenParameters newParameters_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellij.r.psi.rinterop.ScreenParameters, com.intellij.r.psi.rinterop.ScreenParameters.Builder, com.intellij.r.psi.rinterop.ScreenParametersOrBuilder> newParametersBuilder_;
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     * @return Whether the newParameters field is set.
     */
    public boolean hasNewParameters() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     * @return The newParameters.
     */
    public com.intellij.r.psi.rinterop.ScreenParameters getNewParameters() {
      if (newParametersBuilder_ == null) {
        return newParameters_ == null ? com.intellij.r.psi.rinterop.ScreenParameters.getDefaultInstance() : newParameters_;
      } else {
        return newParametersBuilder_.getMessage();
      }
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public Builder setNewParameters(com.intellij.r.psi.rinterop.ScreenParameters value) {
      if (newParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        newParameters_ = value;
      } else {
        newParametersBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public Builder setNewParameters(
        com.intellij.r.psi.rinterop.ScreenParameters.Builder builderForValue) {
      if (newParametersBuilder_ == null) {
        newParameters_ = builderForValue.build();
      } else {
        newParametersBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public Builder mergeNewParameters(com.intellij.r.psi.rinterop.ScreenParameters value) {
      if (newParametersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          newParameters_ != null &&
          newParameters_ != com.intellij.r.psi.rinterop.ScreenParameters.getDefaultInstance()) {
          getNewParametersBuilder().mergeFrom(value);
        } else {
          newParameters_ = value;
        }
      } else {
        newParametersBuilder_.mergeFrom(value);
      }
      if (newParameters_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public Builder clearNewParameters() {
      bitField0_ = (bitField0_ & ~0x00000002);
      newParameters_ = null;
      if (newParametersBuilder_ != null) {
        newParametersBuilder_.dispose();
        newParametersBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public com.intellij.r.psi.rinterop.ScreenParameters.Builder getNewParametersBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNewParametersFieldBuilder().getBuilder();
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    public com.intellij.r.psi.rinterop.ScreenParametersOrBuilder getNewParametersOrBuilder() {
      if (newParametersBuilder_ != null) {
        return newParametersBuilder_.getMessageOrBuilder();
      } else {
        return newParameters_ == null ?
            com.intellij.r.psi.rinterop.ScreenParameters.getDefaultInstance() : newParameters_;
      }
    }
    /**
     * <code>.rplugininterop.ScreenParameters newParameters = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.intellij.r.psi.rinterop.ScreenParameters, com.intellij.r.psi.rinterop.ScreenParameters.Builder, com.intellij.r.psi.rinterop.ScreenParametersOrBuilder> 
        getNewParametersFieldBuilder() {
      if (newParametersBuilder_ == null) {
        newParametersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.intellij.r.psi.rinterop.ScreenParameters, com.intellij.r.psi.rinterop.ScreenParameters.Builder, com.intellij.r.psi.rinterop.ScreenParametersOrBuilder>(
                getNewParameters(),
                getParentForChildren(),
                isClean());
        newParameters_ = null;
      }
      return newParametersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.GraphicsRescaleRequest)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.GraphicsRescaleRequest)
  private static final com.intellij.r.psi.rinterop.GraphicsRescaleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellij.r.psi.rinterop.GraphicsRescaleRequest();
  }

  public static com.intellij.r.psi.rinterop.GraphicsRescaleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GraphicsRescaleRequest>
      PARSER = new com.google.protobuf.AbstractParser<GraphicsRescaleRequest>() {
    @java.lang.Override
    public GraphicsRescaleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GraphicsRescaleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GraphicsRescaleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellij.r.psi.rinterop.GraphicsRescaleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

