// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

/**
 * Protobuf type {@code rplugininterop.PathFigure}
 */
public final class PathFigure extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.PathFigure)
    PathFigureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PathFigure.newBuilder() to construct.
  private PathFigure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PathFigure() {
    subPath_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PathFigure();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_PathFigure_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_PathFigure_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.intellij.r.psi.rinterop.PathFigure.class, com.intellij.r.psi.rinterop.PathFigure.Builder.class);
  }

  public static final int SUBPATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.intellij.r.psi.rinterop.Polyline> subPath_;
  /**
   * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.intellij.r.psi.rinterop.Polyline> getSubPathList() {
    return subPath_;
  }
  /**
   * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.intellij.r.psi.rinterop.PolylineOrBuilder> 
      getSubPathOrBuilderList() {
    return subPath_;
  }
  /**
   * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
   */
  @java.lang.Override
  public int getSubPathCount() {
    return subPath_.size();
  }
  /**
   * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.Polyline getSubPath(int index) {
    return subPath_.get(index);
  }
  /**
   * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
   */
  @java.lang.Override
  public com.intellij.r.psi.rinterop.PolylineOrBuilder getSubPathOrBuilder(
      int index) {
    return subPath_.get(index);
  }

  public static final int WINDING_FIELD_NUMBER = 2;
  private boolean winding_ = false;
  /**
   * <code>bool winding = 2;</code>
   * @return The winding.
   */
  @java.lang.Override
  public boolean getWinding() {
    return winding_;
  }

  public static final int STROKEINDEX_FIELD_NUMBER = 3;
  private int strokeIndex_ = 0;
  /**
   * <code>int32 strokeIndex = 3;</code>
   * @return The strokeIndex.
   */
  @java.lang.Override
  public int getStrokeIndex() {
    return strokeIndex_;
  }

  public static final int COLORINDEX_FIELD_NUMBER = 4;
  private int colorIndex_ = 0;
  /**
   * <code>int32 colorIndex = 4;</code>
   * @return The colorIndex.
   */
  @java.lang.Override
  public int getColorIndex() {
    return colorIndex_;
  }

  public static final int FILLINDEX_FIELD_NUMBER = 5;
  private int fillIndex_ = 0;
  /**
   * <code>int32 fillIndex = 5;</code>
   * @return The fillIndex.
   */
  @java.lang.Override
  public int getFillIndex() {
    return fillIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < subPath_.size(); i++) {
      output.writeMessage(1, subPath_.get(i));
    }
    if (winding_ != false) {
      output.writeBool(2, winding_);
    }
    if (strokeIndex_ != 0) {
      output.writeInt32(3, strokeIndex_);
    }
    if (colorIndex_ != 0) {
      output.writeInt32(4, colorIndex_);
    }
    if (fillIndex_ != 0) {
      output.writeInt32(5, fillIndex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < subPath_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, subPath_.get(i));
    }
    if (winding_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, winding_);
    }
    if (strokeIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, strokeIndex_);
    }
    if (colorIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, colorIndex_);
    }
    if (fillIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, fillIndex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.intellij.r.psi.rinterop.PathFigure)) {
      return super.equals(obj);
    }
    com.intellij.r.psi.rinterop.PathFigure other = (com.intellij.r.psi.rinterop.PathFigure) obj;

    if (!getSubPathList()
        .equals(other.getSubPathList())) return false;
    if (getWinding()
        != other.getWinding()) return false;
    if (getStrokeIndex()
        != other.getStrokeIndex()) return false;
    if (getColorIndex()
        != other.getColorIndex()) return false;
    if (getFillIndex()
        != other.getFillIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubPathCount() > 0) {
      hash = (37 * hash) + SUBPATH_FIELD_NUMBER;
      hash = (53 * hash) + getSubPathList().hashCode();
    }
    hash = (37 * hash) + WINDING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWinding());
    hash = (37 * hash) + STROKEINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getStrokeIndex();
    hash = (37 * hash) + COLORINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getColorIndex();
    hash = (37 * hash) + FILLINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getFillIndex();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.intellij.r.psi.rinterop.PathFigure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.intellij.r.psi.rinterop.PathFigure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.intellij.r.psi.rinterop.PathFigure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.intellij.r.psi.rinterop.PathFigure prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.PathFigure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.PathFigure)
      com.intellij.r.psi.rinterop.PathFigureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_PathFigure_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_PathFigure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.intellij.r.psi.rinterop.PathFigure.class, com.intellij.r.psi.rinterop.PathFigure.Builder.class);
    }

    // Construct using com.intellij.r.psi.rinterop.PathFigure.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (subPathBuilder_ == null) {
        subPath_ = java.util.Collections.emptyList();
      } else {
        subPath_ = null;
        subPathBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      winding_ = false;
      strokeIndex_ = 0;
      colorIndex_ = 0;
      fillIndex_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.intellij.r.psi.rinterop.Service.internal_static_rplugininterop_PathFigure_descriptor;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.PathFigure getDefaultInstanceForType() {
      return com.intellij.r.psi.rinterop.PathFigure.getDefaultInstance();
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.PathFigure build() {
      com.intellij.r.psi.rinterop.PathFigure result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.intellij.r.psi.rinterop.PathFigure buildPartial() {
      com.intellij.r.psi.rinterop.PathFigure result = new com.intellij.r.psi.rinterop.PathFigure(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.intellij.r.psi.rinterop.PathFigure result) {
      if (subPathBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          subPath_ = java.util.Collections.unmodifiableList(subPath_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subPath_ = subPath_;
      } else {
        result.subPath_ = subPathBuilder_.build();
      }
    }

    private void buildPartial0(com.intellij.r.psi.rinterop.PathFigure result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.winding_ = winding_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.strokeIndex_ = strokeIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.colorIndex_ = colorIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.fillIndex_ = fillIndex_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.intellij.r.psi.rinterop.PathFigure) {
        return mergeFrom((com.intellij.r.psi.rinterop.PathFigure)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.intellij.r.psi.rinterop.PathFigure other) {
      if (other == com.intellij.r.psi.rinterop.PathFigure.getDefaultInstance()) return this;
      if (subPathBuilder_ == null) {
        if (!other.subPath_.isEmpty()) {
          if (subPath_.isEmpty()) {
            subPath_ = other.subPath_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubPathIsMutable();
            subPath_.addAll(other.subPath_);
          }
          onChanged();
        }
      } else {
        if (!other.subPath_.isEmpty()) {
          if (subPathBuilder_.isEmpty()) {
            subPathBuilder_.dispose();
            subPathBuilder_ = null;
            subPath_ = other.subPath_;
            bitField0_ = (bitField0_ & ~0x00000001);
            subPathBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubPathFieldBuilder() : null;
          } else {
            subPathBuilder_.addAllMessages(other.subPath_);
          }
        }
      }
      if (other.getWinding() != false) {
        setWinding(other.getWinding());
      }
      if (other.getStrokeIndex() != 0) {
        setStrokeIndex(other.getStrokeIndex());
      }
      if (other.getColorIndex() != 0) {
        setColorIndex(other.getColorIndex());
      }
      if (other.getFillIndex() != 0) {
        setFillIndex(other.getFillIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.intellij.r.psi.rinterop.Polyline m =
                  input.readMessage(
                      com.intellij.r.psi.rinterop.Polyline.parser(),
                      extensionRegistry);
              if (subPathBuilder_ == null) {
                ensureSubPathIsMutable();
                subPath_.add(m);
              } else {
                subPathBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              winding_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              strokeIndex_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              colorIndex_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              fillIndex_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.intellij.r.psi.rinterop.Polyline> subPath_ =
      java.util.Collections.emptyList();
    private void ensureSubPathIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        subPath_ = new java.util.ArrayList<com.intellij.r.psi.rinterop.Polyline>(subPath_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellij.r.psi.rinterop.Polyline, com.intellij.r.psi.rinterop.Polyline.Builder, com.intellij.r.psi.rinterop.PolylineOrBuilder> subPathBuilder_;

    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public java.util.List<com.intellij.r.psi.rinterop.Polyline> getSubPathList() {
      if (subPathBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subPath_);
      } else {
        return subPathBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public int getSubPathCount() {
      if (subPathBuilder_ == null) {
        return subPath_.size();
      } else {
        return subPathBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public com.intellij.r.psi.rinterop.Polyline getSubPath(int index) {
      if (subPathBuilder_ == null) {
        return subPath_.get(index);
      } else {
        return subPathBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder setSubPath(
        int index, com.intellij.r.psi.rinterop.Polyline value) {
      if (subPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubPathIsMutable();
        subPath_.set(index, value);
        onChanged();
      } else {
        subPathBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder setSubPath(
        int index, com.intellij.r.psi.rinterop.Polyline.Builder builderForValue) {
      if (subPathBuilder_ == null) {
        ensureSubPathIsMutable();
        subPath_.set(index, builderForValue.build());
        onChanged();
      } else {
        subPathBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder addSubPath(com.intellij.r.psi.rinterop.Polyline value) {
      if (subPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubPathIsMutable();
        subPath_.add(value);
        onChanged();
      } else {
        subPathBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder addSubPath(
        int index, com.intellij.r.psi.rinterop.Polyline value) {
      if (subPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubPathIsMutable();
        subPath_.add(index, value);
        onChanged();
      } else {
        subPathBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder addSubPath(
        com.intellij.r.psi.rinterop.Polyline.Builder builderForValue) {
      if (subPathBuilder_ == null) {
        ensureSubPathIsMutable();
        subPath_.add(builderForValue.build());
        onChanged();
      } else {
        subPathBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder addSubPath(
        int index, com.intellij.r.psi.rinterop.Polyline.Builder builderForValue) {
      if (subPathBuilder_ == null) {
        ensureSubPathIsMutable();
        subPath_.add(index, builderForValue.build());
        onChanged();
      } else {
        subPathBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder addAllSubPath(
        java.lang.Iterable<? extends com.intellij.r.psi.rinterop.Polyline> values) {
      if (subPathBuilder_ == null) {
        ensureSubPathIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subPath_);
        onChanged();
      } else {
        subPathBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder clearSubPath() {
      if (subPathBuilder_ == null) {
        subPath_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        subPathBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public Builder removeSubPath(int index) {
      if (subPathBuilder_ == null) {
        ensureSubPathIsMutable();
        subPath_.remove(index);
        onChanged();
      } else {
        subPathBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public com.intellij.r.psi.rinterop.Polyline.Builder getSubPathBuilder(
        int index) {
      return getSubPathFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public com.intellij.r.psi.rinterop.PolylineOrBuilder getSubPathOrBuilder(
        int index) {
      if (subPathBuilder_ == null) {
        return subPath_.get(index);  } else {
        return subPathBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public java.util.List<? extends com.intellij.r.psi.rinterop.PolylineOrBuilder> 
         getSubPathOrBuilderList() {
      if (subPathBuilder_ != null) {
        return subPathBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subPath_);
      }
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public com.intellij.r.psi.rinterop.Polyline.Builder addSubPathBuilder() {
      return getSubPathFieldBuilder().addBuilder(
          com.intellij.r.psi.rinterop.Polyline.getDefaultInstance());
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public com.intellij.r.psi.rinterop.Polyline.Builder addSubPathBuilder(
        int index) {
      return getSubPathFieldBuilder().addBuilder(
          index, com.intellij.r.psi.rinterop.Polyline.getDefaultInstance());
    }
    /**
     * <code>repeated .rplugininterop.Polyline subPath = 1;</code>
     */
    public java.util.List<com.intellij.r.psi.rinterop.Polyline.Builder> 
         getSubPathBuilderList() {
      return getSubPathFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.intellij.r.psi.rinterop.Polyline, com.intellij.r.psi.rinterop.Polyline.Builder, com.intellij.r.psi.rinterop.PolylineOrBuilder> 
        getSubPathFieldBuilder() {
      if (subPathBuilder_ == null) {
        subPathBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.intellij.r.psi.rinterop.Polyline, com.intellij.r.psi.rinterop.Polyline.Builder, com.intellij.r.psi.rinterop.PolylineOrBuilder>(
                subPath_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        subPath_ = null;
      }
      return subPathBuilder_;
    }

    private boolean winding_ ;
    /**
     * <code>bool winding = 2;</code>
     * @return The winding.
     */
    @java.lang.Override
    public boolean getWinding() {
      return winding_;
    }
    /**
     * <code>bool winding = 2;</code>
     * @param value The winding to set.
     * @return This builder for chaining.
     */
    public Builder setWinding(boolean value) {

      winding_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool winding = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWinding() {
      bitField0_ = (bitField0_ & ~0x00000002);
      winding_ = false;
      onChanged();
      return this;
    }

    private int strokeIndex_ ;
    /**
     * <code>int32 strokeIndex = 3;</code>
     * @return The strokeIndex.
     */
    @java.lang.Override
    public int getStrokeIndex() {
      return strokeIndex_;
    }
    /**
     * <code>int32 strokeIndex = 3;</code>
     * @param value The strokeIndex to set.
     * @return This builder for chaining.
     */
    public Builder setStrokeIndex(int value) {

      strokeIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 strokeIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrokeIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      strokeIndex_ = 0;
      onChanged();
      return this;
    }

    private int colorIndex_ ;
    /**
     * <code>int32 colorIndex = 4;</code>
     * @return The colorIndex.
     */
    @java.lang.Override
    public int getColorIndex() {
      return colorIndex_;
    }
    /**
     * <code>int32 colorIndex = 4;</code>
     * @param value The colorIndex to set.
     * @return This builder for chaining.
     */
    public Builder setColorIndex(int value) {

      colorIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 colorIndex = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      colorIndex_ = 0;
      onChanged();
      return this;
    }

    private int fillIndex_ ;
    /**
     * <code>int32 fillIndex = 5;</code>
     * @return The fillIndex.
     */
    @java.lang.Override
    public int getFillIndex() {
      return fillIndex_;
    }
    /**
     * <code>int32 fillIndex = 5;</code>
     * @param value The fillIndex to set.
     * @return This builder for chaining.
     */
    public Builder setFillIndex(int value) {

      fillIndex_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fillIndex = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFillIndex() {
      bitField0_ = (bitField0_ & ~0x00000010);
      fillIndex_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.PathFigure)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.PathFigure)
  private static final com.intellij.r.psi.rinterop.PathFigure DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.intellij.r.psi.rinterop.PathFigure();
  }

  public static com.intellij.r.psi.rinterop.PathFigure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PathFigure>
      PARSER = new com.google.protobuf.AbstractParser<PathFigure>() {
    @java.lang.Override
    public PathFigure parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PathFigure> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PathFigure> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.intellij.r.psi.rinterop.PathFigure getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

