// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.intellij.r.psi.rinterop;

public interface RasterFigureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.RasterFigure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rplugininterop.RasterImage image = 1;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.rplugininterop.RasterImage image = 1;</code>
   * @return The image.
   */
  com.intellij.r.psi.rinterop.RasterImage getImage();
  /**
   * <code>.rplugininterop.RasterImage image = 1;</code>
   */
  com.intellij.r.psi.rinterop.RasterImageOrBuilder getImageOrBuilder();

  /**
   * <code>fixed64 from = 2;</code>
   * @return The from.
   */
  long getFrom();

  /**
   * <code>fixed64 to = 3;</code>
   * @return The to.
   */
  long getTo();

  /**
   * <code>float angle = 4;</code>
   * @return The angle.
   */
  float getAngle();

  /**
   * <code>bool interpolate = 5;</code>
   * @return The interpolate.
   */
  boolean getInterpolate();
}
