// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface ChunkParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.ChunkParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rmarkdownParameters = 1;</code>
   */
  java.lang.String getRmarkdownParameters();
  /**
   * <code>string rmarkdownParameters = 1;</code>
   */
  com.google.protobuf.ByteString
      getRmarkdownParametersBytes();

  /**
   * <code>string chunkText = 2;</code>
   */
  java.lang.String getChunkText();
  /**
   * <code>string chunkText = 2;</code>
   */
  com.google.protobuf.ByteString
      getChunkTextBytes();

  /**
   * <code>string outputDirectory = 3;</code>
   */
  java.lang.String getOutputDirectory();
  /**
   * <code>string outputDirectory = 3;</code>
   */
  com.google.protobuf.ByteString
      getOutputDirectoryBytes();

  /**
   * <code>int32 width = 4;</code>
   */
  int getWidth();

  /**
   * <code>int32 height = 5;</code>
   */
  int getHeight();

  /**
   * <code>int32 resolution = 6;</code>
   */
  int getResolution();
}
