// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface CircleFigureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.CircleFigure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rplugininterop.AffinePoint center = 1;</code>
   * @return Whether the center field is set.
   */
  boolean hasCenter();
  /**
   * <code>.rplugininterop.AffinePoint center = 1;</code>
   * @return The center.
   */
  org.jetbrains.r.rinterop.AffinePoint getCenter();
  /**
   * <code>.rplugininterop.AffinePoint center = 1;</code>
   */
  org.jetbrains.r.rinterop.AffinePointOrBuilder getCenterOrBuilder();

  /**
   * <code>float radiusScale = 2;</code>
   * @return The radiusScale.
   */
  float getRadiusScale();

  /**
   * <code>float radiusOffset = 3;</code>
   * @return The radiusOffset.
   */
  float getRadiusOffset();

  /**
   * <code>int32 strokeIndex = 4;</code>
   * @return The strokeIndex.
   */
  int getStrokeIndex();

  /**
   * <code>int32 colorIndex = 5;</code>
   * @return The colorIndex.
   */
  int getColorIndex();

  /**
   * <code>int32 fillIndex = 6;</code>
   * @return The fillIndex.
   */
  int getFillIndex();
}
