// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

/**
 * Protobuf type {@code rplugininterop.DebugAddBreakpointRequest}
 */
public  final class DebugAddBreakpointRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.DebugAddBreakpointRequest)
    DebugAddBreakpointRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DebugAddBreakpointRequest.newBuilder() to construct.
  private DebugAddBreakpointRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DebugAddBreakpointRequest() {
    evaluateAndLog_ = "";
    condition_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DebugAddBreakpointRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DebugAddBreakpointRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.jetbrains.r.rinterop.SourcePosition.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(org.jetbrains.r.rinterop.SourcePosition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            suspend_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            evaluateAndLog_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            condition_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_DebugAddBreakpointRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_DebugAddBreakpointRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.r.rinterop.DebugAddBreakpointRequest.class, org.jetbrains.r.rinterop.DebugAddBreakpointRequest.Builder.class);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  private org.jetbrains.r.rinterop.SourcePosition position_;
  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   */
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   */
  public org.jetbrains.r.rinterop.SourcePosition getPosition() {
    return position_ == null ? org.jetbrains.r.rinterop.SourcePosition.getDefaultInstance() : position_;
  }
  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   */
  public org.jetbrains.r.rinterop.SourcePositionOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int SUSPEND_FIELD_NUMBER = 2;
  private boolean suspend_;
  /**
   * <code>bool suspend = 2;</code>
   */
  public boolean getSuspend() {
    return suspend_;
  }

  public static final int EVALUATEANDLOG_FIELD_NUMBER = 3;
  private volatile java.lang.Object evaluateAndLog_;
  /**
   * <code>string evaluateAndLog = 3;</code>
   */
  public java.lang.String getEvaluateAndLog() {
    java.lang.Object ref = evaluateAndLog_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      evaluateAndLog_ = s;
      return s;
    }
  }
  /**
   * <code>string evaluateAndLog = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEvaluateAndLogBytes() {
    java.lang.Object ref = evaluateAndLog_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      evaluateAndLog_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONDITION_FIELD_NUMBER = 4;
  private volatile java.lang.Object condition_;
  /**
   * <code>string condition = 4;</code>
   */
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <code>string condition = 4;</code>
   */
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (position_ != null) {
      output.writeMessage(1, getPosition());
    }
    if (suspend_ != false) {
      output.writeBool(2, suspend_);
    }
    if (!getEvaluateAndLogBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, evaluateAndLog_);
    }
    if (!getConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, condition_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPosition());
    }
    if (suspend_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, suspend_);
    }
    if (!getEvaluateAndLogBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, evaluateAndLog_);
    }
    if (!getConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, condition_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jetbrains.r.rinterop.DebugAddBreakpointRequest)) {
      return super.equals(obj);
    }
    org.jetbrains.r.rinterop.DebugAddBreakpointRequest other = (org.jetbrains.r.rinterop.DebugAddBreakpointRequest) obj;

    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (getSuspend()
        != other.getSuspend()) return false;
    if (!getEvaluateAndLog()
        .equals(other.getEvaluateAndLog())) return false;
    if (!getCondition()
        .equals(other.getCondition())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + SUSPEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuspend());
    hash = (37 * hash) + EVALUATEANDLOG_FIELD_NUMBER;
    hash = (53 * hash) + getEvaluateAndLog().hashCode();
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jetbrains.r.rinterop.DebugAddBreakpointRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.DebugAddBreakpointRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.DebugAddBreakpointRequest)
      org.jetbrains.r.rinterop.DebugAddBreakpointRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_DebugAddBreakpointRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_DebugAddBreakpointRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.r.rinterop.DebugAddBreakpointRequest.class, org.jetbrains.r.rinterop.DebugAddBreakpointRequest.Builder.class);
    }

    // Construct using org.jetbrains.r.rinterop.DebugAddBreakpointRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      suspend_ = false;

      evaluateAndLog_ = "";

      condition_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_DebugAddBreakpointRequest_descriptor;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.DebugAddBreakpointRequest getDefaultInstanceForType() {
      return org.jetbrains.r.rinterop.DebugAddBreakpointRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.DebugAddBreakpointRequest build() {
      org.jetbrains.r.rinterop.DebugAddBreakpointRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.DebugAddBreakpointRequest buildPartial() {
      org.jetbrains.r.rinterop.DebugAddBreakpointRequest result = new org.jetbrains.r.rinterop.DebugAddBreakpointRequest(this);
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      result.suspend_ = suspend_;
      result.evaluateAndLog_ = evaluateAndLog_;
      result.condition_ = condition_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jetbrains.r.rinterop.DebugAddBreakpointRequest) {
        return mergeFrom((org.jetbrains.r.rinterop.DebugAddBreakpointRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.r.rinterop.DebugAddBreakpointRequest other) {
      if (other == org.jetbrains.r.rinterop.DebugAddBreakpointRequest.getDefaultInstance()) return this;
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.getSuspend() != false) {
        setSuspend(other.getSuspend());
      }
      if (!other.getEvaluateAndLog().isEmpty()) {
        evaluateAndLog_ = other.evaluateAndLog_;
        onChanged();
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.r.rinterop.DebugAddBreakpointRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.r.rinterop.DebugAddBreakpointRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.jetbrains.r.rinterop.SourcePosition position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.SourcePosition, org.jetbrains.r.rinterop.SourcePosition.Builder, org.jetbrains.r.rinterop.SourcePositionOrBuilder> positionBuilder_;
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public org.jetbrains.r.rinterop.SourcePosition getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? org.jetbrains.r.rinterop.SourcePosition.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public Builder setPosition(org.jetbrains.r.rinterop.SourcePosition value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public Builder setPosition(
        org.jetbrains.r.rinterop.SourcePosition.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public Builder mergePosition(org.jetbrains.r.rinterop.SourcePosition value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            org.jetbrains.r.rinterop.SourcePosition.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public org.jetbrains.r.rinterop.SourcePosition.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    public org.jetbrains.r.rinterop.SourcePositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            org.jetbrains.r.rinterop.SourcePosition.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.rplugininterop.SourcePosition position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.SourcePosition, org.jetbrains.r.rinterop.SourcePosition.Builder, org.jetbrains.r.rinterop.SourcePositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.jetbrains.r.rinterop.SourcePosition, org.jetbrains.r.rinterop.SourcePosition.Builder, org.jetbrains.r.rinterop.SourcePositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private boolean suspend_ ;
    /**
     * <code>bool suspend = 2;</code>
     */
    public boolean getSuspend() {
      return suspend_;
    }
    /**
     * <code>bool suspend = 2;</code>
     */
    public Builder setSuspend(boolean value) {
      
      suspend_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool suspend = 2;</code>
     */
    public Builder clearSuspend() {
      
      suspend_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object evaluateAndLog_ = "";
    /**
     * <code>string evaluateAndLog = 3;</code>
     */
    public java.lang.String getEvaluateAndLog() {
      java.lang.Object ref = evaluateAndLog_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evaluateAndLog_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string evaluateAndLog = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEvaluateAndLogBytes() {
      java.lang.Object ref = evaluateAndLog_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evaluateAndLog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string evaluateAndLog = 3;</code>
     */
    public Builder setEvaluateAndLog(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      evaluateAndLog_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string evaluateAndLog = 3;</code>
     */
    public Builder clearEvaluateAndLog() {
      
      evaluateAndLog_ = getDefaultInstance().getEvaluateAndLog();
      onChanged();
      return this;
    }
    /**
     * <code>string evaluateAndLog = 3;</code>
     */
    public Builder setEvaluateAndLogBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      evaluateAndLog_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <code>string condition = 4;</code>
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string condition = 4;</code>
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string condition = 4;</code>
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      condition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 4;</code>
     */
    public Builder clearCondition() {
      
      condition_ = getDefaultInstance().getCondition();
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 4;</code>
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      condition_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.DebugAddBreakpointRequest)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.DebugAddBreakpointRequest)
  private static final org.jetbrains.r.rinterop.DebugAddBreakpointRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jetbrains.r.rinterop.DebugAddBreakpointRequest();
  }

  public static org.jetbrains.r.rinterop.DebugAddBreakpointRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DebugAddBreakpointRequest>
      PARSER = new com.google.protobuf.AbstractParser<DebugAddBreakpointRequest>() {
    @java.lang.Override
    public DebugAddBreakpointRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DebugAddBreakpointRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DebugAddBreakpointRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DebugAddBreakpointRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jetbrains.r.rinterop.DebugAddBreakpointRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

