// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface DebugAddOrModifyBreakpointRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.DebugAddOrModifyBreakpointRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>.rplugininterop.SourcePosition position = 2;</code>
   */
  boolean hasPosition();
  /**
   * <code>.rplugininterop.SourcePosition position = 2;</code>
   */
  org.jetbrains.r.rinterop.SourcePosition getPosition();
  /**
   * <code>.rplugininterop.SourcePosition position = 2;</code>
   */
  org.jetbrains.r.rinterop.SourcePositionOrBuilder getPositionOrBuilder();

  /**
   * <code>bool enabled = 3;</code>
   */
  boolean getEnabled();

  /**
   * <code>bool suspend = 4;</code>
   */
  boolean getSuspend();

  /**
   * <code>string evaluateAndLog = 5;</code>
   */
  java.lang.String getEvaluateAndLog();
  /**
   * <code>string evaluateAndLog = 5;</code>
   */
  com.google.protobuf.ByteString
      getEvaluateAndLogBytes();

  /**
   * <code>string condition = 6;</code>
   */
  java.lang.String getCondition();
  /**
   * <code>string condition = 6;</code>
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <code>bool removeAfterHit = 7;</code>
   */
  boolean getRemoveAfterHit();

  /**
   * <code>bool hitMessage = 8;</code>
   */
  boolean getHitMessage();

  /**
   * <code>bool printStack = 9;</code>
   */
  boolean getPrintStack();
}
