// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface DocumentationForSymbolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.DocumentationForSymbolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string package = 2;</code>
   */
  java.lang.String getPackage();
  /**
   * <code>string package = 2;</code>
   */
  com.google.protobuf.ByteString
      getPackageBytes();
}
