// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

/**
 * Protobuf type {@code rplugininterop.ExceptionInfo}
 */
public final class ExceptionInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.ExceptionInfo)
    ExceptionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExceptionInfo.newBuilder() to construct.
  private ExceptionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExceptionInfo() {
    message_ = "";
    call_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExceptionInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExceptionInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            call_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Empty.Builder subBuilder = null;
            if (detailsCase_ == 3) {
              subBuilder = ((com.google.protobuf.Empty) details_).toBuilder();
            }
            details_ =
                input.readMessage(com.google.protobuf.Empty.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Empty) details_);
              details_ = subBuilder.buildPartial();
            }
            detailsCase_ = 3;
            break;
          }
          case 34: {
            com.google.protobuf.Empty.Builder subBuilder = null;
            if (detailsCase_ == 4) {
              subBuilder = ((com.google.protobuf.Empty) details_).toBuilder();
            }
            details_ =
                input.readMessage(com.google.protobuf.Empty.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Empty) details_);
              details_ = subBuilder.buildPartial();
            }
            detailsCase_ = 4;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            detailsCase_ = 5;
            details_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ExceptionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ExceptionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.r.rinterop.ExceptionInfo.class, org.jetbrains.r.rinterop.ExceptionInfo.Builder.class);
  }

  private int detailsCase_ = 0;
  private java.lang.Object details_;
  public enum DetailsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SIMPLEERROR(3),
    INTERRUPTED(4),
    PACKAGENOTFOUND(5),
    DETAILS_NOT_SET(0);
    private final int value;
    private DetailsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DetailsCase valueOf(int value) {
      return forNumber(value);
    }

    public static DetailsCase forNumber(int value) {
      switch (value) {
        case 3: return SIMPLEERROR;
        case 4: return INTERRUPTED;
        case 5: return PACKAGENOTFOUND;
        case 0: return DETAILS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DetailsCase
  getDetailsCase() {
    return DetailsCase.forNumber(
        detailsCase_);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALL_FIELD_NUMBER = 2;
  private volatile java.lang.Object call_;
  /**
   * <code>string call = 2;</code>
   * @return The call.
   */
  @java.lang.Override
  public java.lang.String getCall() {
    java.lang.Object ref = call_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      call_ = s;
      return s;
    }
  }
  /**
   * <code>string call = 2;</code>
   * @return The bytes for call.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallBytes() {
    java.lang.Object ref = call_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      call_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIMPLEERROR_FIELD_NUMBER = 3;
  /**
   * <code>.google.protobuf.Empty simpleError = 3;</code>
   * @return Whether the simpleError field is set.
   */
  @java.lang.Override
  public boolean hasSimpleError() {
    return detailsCase_ == 3;
  }
  /**
   * <code>.google.protobuf.Empty simpleError = 3;</code>
   * @return The simpleError.
   */
  @java.lang.Override
  public com.google.protobuf.Empty getSimpleError() {
    if (detailsCase_ == 3) {
       return (com.google.protobuf.Empty) details_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Empty simpleError = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.EmptyOrBuilder getSimpleErrorOrBuilder() {
    if (detailsCase_ == 3) {
       return (com.google.protobuf.Empty) details_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }

  public static final int INTERRUPTED_FIELD_NUMBER = 4;
  /**
   * <code>.google.protobuf.Empty interrupted = 4;</code>
   * @return Whether the interrupted field is set.
   */
  @java.lang.Override
  public boolean hasInterrupted() {
    return detailsCase_ == 4;
  }
  /**
   * <code>.google.protobuf.Empty interrupted = 4;</code>
   * @return The interrupted.
   */
  @java.lang.Override
  public com.google.protobuf.Empty getInterrupted() {
    if (detailsCase_ == 4) {
       return (com.google.protobuf.Empty) details_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Empty interrupted = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.EmptyOrBuilder getInterruptedOrBuilder() {
    if (detailsCase_ == 4) {
       return (com.google.protobuf.Empty) details_;
    }
    return com.google.protobuf.Empty.getDefaultInstance();
  }

  public static final int PACKAGENOTFOUND_FIELD_NUMBER = 5;
  /**
   * <code>string packageNotFound = 5;</code>
   * @return The packageNotFound.
   */
  public java.lang.String getPackageNotFound() {
    java.lang.Object ref = "";
    if (detailsCase_ == 5) {
      ref = details_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (detailsCase_ == 5) {
        details_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string packageNotFound = 5;</code>
   * @return The bytes for packageNotFound.
   */
  public com.google.protobuf.ByteString
      getPackageNotFoundBytes() {
    java.lang.Object ref = "";
    if (detailsCase_ == 5) {
      ref = details_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (detailsCase_ == 5) {
        details_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (!getCallBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, call_);
    }
    if (detailsCase_ == 3) {
      output.writeMessage(3, (com.google.protobuf.Empty) details_);
    }
    if (detailsCase_ == 4) {
      output.writeMessage(4, (com.google.protobuf.Empty) details_);
    }
    if (detailsCase_ == 5) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, details_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (!getCallBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, call_);
    }
    if (detailsCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.protobuf.Empty) details_);
    }
    if (detailsCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.google.protobuf.Empty) details_);
    }
    if (detailsCase_ == 5) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, details_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jetbrains.r.rinterop.ExceptionInfo)) {
      return super.equals(obj);
    }
    org.jetbrains.r.rinterop.ExceptionInfo other = (org.jetbrains.r.rinterop.ExceptionInfo) obj;

    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getCall()
        .equals(other.getCall())) return false;
    if (!getDetailsCase().equals(other.getDetailsCase())) return false;
    switch (detailsCase_) {
      case 3:
        if (!getSimpleError()
            .equals(other.getSimpleError())) return false;
        break;
      case 4:
        if (!getInterrupted()
            .equals(other.getInterrupted())) return false;
        break;
      case 5:
        if (!getPackageNotFound()
            .equals(other.getPackageNotFound())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + CALL_FIELD_NUMBER;
    hash = (53 * hash) + getCall().hashCode();
    switch (detailsCase_) {
      case 3:
        hash = (37 * hash) + SIMPLEERROR_FIELD_NUMBER;
        hash = (53 * hash) + getSimpleError().hashCode();
        break;
      case 4:
        hash = (37 * hash) + INTERRUPTED_FIELD_NUMBER;
        hash = (53 * hash) + getInterrupted().hashCode();
        break;
      case 5:
        hash = (37 * hash) + PACKAGENOTFOUND_FIELD_NUMBER;
        hash = (53 * hash) + getPackageNotFound().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ExceptionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jetbrains.r.rinterop.ExceptionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.ExceptionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.ExceptionInfo)
      org.jetbrains.r.rinterop.ExceptionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ExceptionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ExceptionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.r.rinterop.ExceptionInfo.class, org.jetbrains.r.rinterop.ExceptionInfo.Builder.class);
    }

    // Construct using org.jetbrains.r.rinterop.ExceptionInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      message_ = "";

      call_ = "";

      detailsCase_ = 0;
      details_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ExceptionInfo_descriptor;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ExceptionInfo getDefaultInstanceForType() {
      return org.jetbrains.r.rinterop.ExceptionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ExceptionInfo build() {
      org.jetbrains.r.rinterop.ExceptionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ExceptionInfo buildPartial() {
      org.jetbrains.r.rinterop.ExceptionInfo result = new org.jetbrains.r.rinterop.ExceptionInfo(this);
      result.message_ = message_;
      result.call_ = call_;
      if (detailsCase_ == 3) {
        if (simpleErrorBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = simpleErrorBuilder_.build();
        }
      }
      if (detailsCase_ == 4) {
        if (interruptedBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = interruptedBuilder_.build();
        }
      }
      if (detailsCase_ == 5) {
        result.details_ = details_;
      }
      result.detailsCase_ = detailsCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jetbrains.r.rinterop.ExceptionInfo) {
        return mergeFrom((org.jetbrains.r.rinterop.ExceptionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.r.rinterop.ExceptionInfo other) {
      if (other == org.jetbrains.r.rinterop.ExceptionInfo.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getCall().isEmpty()) {
        call_ = other.call_;
        onChanged();
      }
      switch (other.getDetailsCase()) {
        case SIMPLEERROR: {
          mergeSimpleError(other.getSimpleError());
          break;
        }
        case INTERRUPTED: {
          mergeInterrupted(other.getInterrupted());
          break;
        }
        case PACKAGENOTFOUND: {
          detailsCase_ = 5;
          details_ = other.details_;
          onChanged();
          break;
        }
        case DETAILS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.r.rinterop.ExceptionInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.r.rinterop.ExceptionInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int detailsCase_ = 0;
    private java.lang.Object details_;
    public DetailsCase
        getDetailsCase() {
      return DetailsCase.forNumber(
          detailsCase_);
    }

    public Builder clearDetails() {
      detailsCase_ = 0;
      details_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object call_ = "";
    /**
     * <code>string call = 2;</code>
     * @return The call.
     */
    public java.lang.String getCall() {
      java.lang.Object ref = call_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        call_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string call = 2;</code>
     * @return The bytes for call.
     */
    public com.google.protobuf.ByteString
        getCallBytes() {
      java.lang.Object ref = call_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        call_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string call = 2;</code>
     * @param value The call to set.
     * @return This builder for chaining.
     */
    public Builder setCall(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      call_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string call = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCall() {
      
      call_ = getDefaultInstance().getCall();
      onChanged();
      return this;
    }
    /**
     * <code>string call = 2;</code>
     * @param value The bytes for call to set.
     * @return This builder for chaining.
     */
    public Builder setCallBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      call_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> simpleErrorBuilder_;
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     * @return Whether the simpleError field is set.
     */
    @java.lang.Override
    public boolean hasSimpleError() {
      return detailsCase_ == 3;
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     * @return The simpleError.
     */
    @java.lang.Override
    public com.google.protobuf.Empty getSimpleError() {
      if (simpleErrorBuilder_ == null) {
        if (detailsCase_ == 3) {
          return (com.google.protobuf.Empty) details_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      } else {
        if (detailsCase_ == 3) {
          return simpleErrorBuilder_.getMessage();
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    public Builder setSimpleError(com.google.protobuf.Empty value) {
      if (simpleErrorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        details_ = value;
        onChanged();
      } else {
        simpleErrorBuilder_.setMessage(value);
      }
      detailsCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    public Builder setSimpleError(
        com.google.protobuf.Empty.Builder builderForValue) {
      if (simpleErrorBuilder_ == null) {
        details_ = builderForValue.build();
        onChanged();
      } else {
        simpleErrorBuilder_.setMessage(builderForValue.build());
      }
      detailsCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    public Builder mergeSimpleError(com.google.protobuf.Empty value) {
      if (simpleErrorBuilder_ == null) {
        if (detailsCase_ == 3 &&
            details_ != com.google.protobuf.Empty.getDefaultInstance()) {
          details_ = com.google.protobuf.Empty.newBuilder((com.google.protobuf.Empty) details_)
              .mergeFrom(value).buildPartial();
        } else {
          details_ = value;
        }
        onChanged();
      } else {
        if (detailsCase_ == 3) {
          simpleErrorBuilder_.mergeFrom(value);
        }
        simpleErrorBuilder_.setMessage(value);
      }
      detailsCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    public Builder clearSimpleError() {
      if (simpleErrorBuilder_ == null) {
        if (detailsCase_ == 3) {
          detailsCase_ = 0;
          details_ = null;
          onChanged();
        }
      } else {
        if (detailsCase_ == 3) {
          detailsCase_ = 0;
          details_ = null;
        }
        simpleErrorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    public com.google.protobuf.Empty.Builder getSimpleErrorBuilder() {
      return getSimpleErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.EmptyOrBuilder getSimpleErrorOrBuilder() {
      if ((detailsCase_ == 3) && (simpleErrorBuilder_ != null)) {
        return simpleErrorBuilder_.getMessageOrBuilder();
      } else {
        if (detailsCase_ == 3) {
          return (com.google.protobuf.Empty) details_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Empty simpleError = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
        getSimpleErrorFieldBuilder() {
      if (simpleErrorBuilder_ == null) {
        if (!(detailsCase_ == 3)) {
          details_ = com.google.protobuf.Empty.getDefaultInstance();
        }
        simpleErrorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                (com.google.protobuf.Empty) details_,
                getParentForChildren(),
                isClean());
        details_ = null;
      }
      detailsCase_ = 3;
      onChanged();;
      return simpleErrorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> interruptedBuilder_;
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     * @return Whether the interrupted field is set.
     */
    @java.lang.Override
    public boolean hasInterrupted() {
      return detailsCase_ == 4;
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     * @return The interrupted.
     */
    @java.lang.Override
    public com.google.protobuf.Empty getInterrupted() {
      if (interruptedBuilder_ == null) {
        if (detailsCase_ == 4) {
          return (com.google.protobuf.Empty) details_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      } else {
        if (detailsCase_ == 4) {
          return interruptedBuilder_.getMessage();
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    public Builder setInterrupted(com.google.protobuf.Empty value) {
      if (interruptedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        details_ = value;
        onChanged();
      } else {
        interruptedBuilder_.setMessage(value);
      }
      detailsCase_ = 4;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    public Builder setInterrupted(
        com.google.protobuf.Empty.Builder builderForValue) {
      if (interruptedBuilder_ == null) {
        details_ = builderForValue.build();
        onChanged();
      } else {
        interruptedBuilder_.setMessage(builderForValue.build());
      }
      detailsCase_ = 4;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    public Builder mergeInterrupted(com.google.protobuf.Empty value) {
      if (interruptedBuilder_ == null) {
        if (detailsCase_ == 4 &&
            details_ != com.google.protobuf.Empty.getDefaultInstance()) {
          details_ = com.google.protobuf.Empty.newBuilder((com.google.protobuf.Empty) details_)
              .mergeFrom(value).buildPartial();
        } else {
          details_ = value;
        }
        onChanged();
      } else {
        if (detailsCase_ == 4) {
          interruptedBuilder_.mergeFrom(value);
        }
        interruptedBuilder_.setMessage(value);
      }
      detailsCase_ = 4;
      return this;
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    public Builder clearInterrupted() {
      if (interruptedBuilder_ == null) {
        if (detailsCase_ == 4) {
          detailsCase_ = 0;
          details_ = null;
          onChanged();
        }
      } else {
        if (detailsCase_ == 4) {
          detailsCase_ = 0;
          details_ = null;
        }
        interruptedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    public com.google.protobuf.Empty.Builder getInterruptedBuilder() {
      return getInterruptedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.EmptyOrBuilder getInterruptedOrBuilder() {
      if ((detailsCase_ == 4) && (interruptedBuilder_ != null)) {
        return interruptedBuilder_.getMessageOrBuilder();
      } else {
        if (detailsCase_ == 4) {
          return (com.google.protobuf.Empty) details_;
        }
        return com.google.protobuf.Empty.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Empty interrupted = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
        getInterruptedFieldBuilder() {
      if (interruptedBuilder_ == null) {
        if (!(detailsCase_ == 4)) {
          details_ = com.google.protobuf.Empty.getDefaultInstance();
        }
        interruptedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                (com.google.protobuf.Empty) details_,
                getParentForChildren(),
                isClean());
        details_ = null;
      }
      detailsCase_ = 4;
      onChanged();;
      return interruptedBuilder_;
    }

    /**
     * <code>string packageNotFound = 5;</code>
     * @return The packageNotFound.
     */
    @java.lang.Override
    public java.lang.String getPackageNotFound() {
      java.lang.Object ref = "";
      if (detailsCase_ == 5) {
        ref = details_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (detailsCase_ == 5) {
          details_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string packageNotFound = 5;</code>
     * @return The bytes for packageNotFound.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPackageNotFoundBytes() {
      java.lang.Object ref = "";
      if (detailsCase_ == 5) {
        ref = details_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (detailsCase_ == 5) {
          details_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string packageNotFound = 5;</code>
     * @param value The packageNotFound to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNotFound(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  detailsCase_ = 5;
      details_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string packageNotFound = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageNotFound() {
      if (detailsCase_ == 5) {
        detailsCase_ = 0;
        details_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string packageNotFound = 5;</code>
     * @param value The bytes for packageNotFound to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNotFoundBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      detailsCase_ = 5;
      details_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.ExceptionInfo)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.ExceptionInfo)
  private static final org.jetbrains.r.rinterop.ExceptionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jetbrains.r.rinterop.ExceptionInfo();
  }

  public static org.jetbrains.r.rinterop.ExceptionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExceptionInfo>
      PARSER = new com.google.protobuf.AbstractParser<ExceptionInfo>() {
    @java.lang.Override
    public ExceptionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExceptionInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExceptionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExceptionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jetbrains.r.rinterop.ExceptionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

