// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface ExtraNamedArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.ExtraNamedArguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * See org.jetbrains.r.hints.parameterInfo.RExtraNamedArgumentsInfo for details
   * </pre>
   *
   * <code>repeated string argNames = 1;</code>
   * @return A list containing the argNames.
   */
  java.util.List<java.lang.String>
      getArgNamesList();
  /**
   * <pre>
   * See org.jetbrains.r.hints.parameterInfo.RExtraNamedArgumentsInfo for details
   * </pre>
   *
   * <code>repeated string argNames = 1;</code>
   * @return The count of argNames.
   */
  int getArgNamesCount();
  /**
   * <pre>
   * See org.jetbrains.r.hints.parameterInfo.RExtraNamedArgumentsInfo for details
   * </pre>
   *
   * <code>repeated string argNames = 1;</code>
   * @param index The index of the element to return.
   * @return The argNames at the given index.
   */
  java.lang.String getArgNames(int index);
  /**
   * <pre>
   * See org.jetbrains.r.hints.parameterInfo.RExtraNamedArgumentsInfo for details
   * </pre>
   *
   * <code>repeated string argNames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the argNames at the given index.
   */
  com.google.protobuf.ByteString
      getArgNamesBytes(int index);

  /**
   * <code>repeated string funArgNames = 2;</code>
   * @return A list containing the funArgNames.
   */
  java.util.List<java.lang.String>
      getFunArgNamesList();
  /**
   * <code>repeated string funArgNames = 2;</code>
   * @return The count of funArgNames.
   */
  int getFunArgNamesCount();
  /**
   * <code>repeated string funArgNames = 2;</code>
   * @param index The index of the element to return.
   * @return The funArgNames at the given index.
   */
  java.lang.String getFunArgNames(int index);
  /**
   * <code>repeated string funArgNames = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the funArgNames at the given index.
   */
  com.google.protobuf.ByteString
      getFunArgNamesBytes(int index);
}
