// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface GetVariablesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.GetVariablesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   * @return Whether the obj field is set.
   */
  boolean hasObj();
  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   * @return The obj.
   */
  org.jetbrains.r.rinterop.RRef getObj();
  /**
   * <code>.rplugininterop.RRef obj = 1;</code>
   */
  org.jetbrains.r.rinterop.RRefOrBuilder getObjOrBuilder();

  /**
   * <code>int64 start = 2;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>int64 end = 3;</code>
   * @return The end.
   */
  long getEnd();

  /**
   * <pre>
   * These parameters are for environments only
   * </pre>
   *
   * <code>bool noHidden = 4;</code>
   * @return The noHidden.
   */
  boolean getNoHidden();

  /**
   * <code>bool noFunctions = 5;</code>
   * @return The noFunctions.
   */
  boolean getNoFunctions();

  /**
   * <code>bool onlyFunctions = 6;</code>
   * @return The onlyFunctions.
   */
  boolean getOnlyFunctions();
}
