// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

/**
 * Protobuf type {@code rplugininterop.ParentEnvsResponse}
 */
public  final class ParentEnvsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.ParentEnvsResponse)
    ParentEnvsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParentEnvsResponse.newBuilder() to construct.
  private ParentEnvsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParentEnvsResponse() {
    envs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParentEnvsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParentEnvsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              envs_ = new java.util.ArrayList<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            envs_.add(
                input.readMessage(org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        envs_ = java.util.Collections.unmodifiableList(envs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.r.rinterop.ParentEnvsResponse.class, org.jetbrains.r.rinterop.ParentEnvsResponse.Builder.class);
  }

  public interface EnvInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rplugininterop.ParentEnvsResponse.EnvInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code rplugininterop.ParentEnvsResponse.EnvInfo}
   */
  public  static final class EnvInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rplugininterop.ParentEnvsResponse.EnvInfo)
      EnvInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvInfo.newBuilder() to construct.
    private EnvInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvInfo() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EnvInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_EnvInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_EnvInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.class, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo)) {
        return super.equals(obj);
      }
      org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo other = (org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rplugininterop.ParentEnvsResponse.EnvInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rplugininterop.ParentEnvsResponse.EnvInfo)
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_EnvInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_EnvInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.class, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder.class);
      }

      // Construct using org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_EnvInfo_descriptor;
      }

      @java.lang.Override
      public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo getDefaultInstanceForType() {
        return org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo build() {
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo buildPartial() {
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo result = new org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo) {
          return mergeFrom((org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo other) {
        if (other == org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rplugininterop.ParentEnvsResponse.EnvInfo)
    }

    // @@protoc_insertion_point(class_scope:rplugininterop.ParentEnvsResponse.EnvInfo)
    private static final org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo();
    }

    public static org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvInfo>
        PARSER = new com.google.protobuf.AbstractParser<EnvInfo>() {
      @java.lang.Override
      public EnvInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ENVS_FIELD_NUMBER = 1;
  private java.util.List<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo> envs_;
  /**
   * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
   */
  public java.util.List<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo> getEnvsList() {
    return envs_;
  }
  /**
   * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
   */
  public java.util.List<? extends org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder> 
      getEnvsOrBuilderList() {
    return envs_;
  }
  /**
   * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
   */
  public int getEnvsCount() {
    return envs_.size();
  }
  /**
   * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
   */
  public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo getEnvs(int index) {
    return envs_.get(index);
  }
  /**
   * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
   */
  public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder getEnvsOrBuilder(
      int index) {
    return envs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < envs_.size(); i++) {
      output.writeMessage(1, envs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < envs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, envs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jetbrains.r.rinterop.ParentEnvsResponse)) {
      return super.equals(obj);
    }
    org.jetbrains.r.rinterop.ParentEnvsResponse other = (org.jetbrains.r.rinterop.ParentEnvsResponse) obj;

    if (!getEnvsList()
        .equals(other.getEnvsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEnvsCount() > 0) {
      hash = (37 * hash) + ENVS_FIELD_NUMBER;
      hash = (53 * hash) + getEnvsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.ParentEnvsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jetbrains.r.rinterop.ParentEnvsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.ParentEnvsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.ParentEnvsResponse)
      org.jetbrains.r.rinterop.ParentEnvsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.r.rinterop.ParentEnvsResponse.class, org.jetbrains.r.rinterop.ParentEnvsResponse.Builder.class);
    }

    // Construct using org.jetbrains.r.rinterop.ParentEnvsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEnvsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (envsBuilder_ == null) {
        envs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        envsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_ParentEnvsResponse_descriptor;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ParentEnvsResponse getDefaultInstanceForType() {
      return org.jetbrains.r.rinterop.ParentEnvsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ParentEnvsResponse build() {
      org.jetbrains.r.rinterop.ParentEnvsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.ParentEnvsResponse buildPartial() {
      org.jetbrains.r.rinterop.ParentEnvsResponse result = new org.jetbrains.r.rinterop.ParentEnvsResponse(this);
      int from_bitField0_ = bitField0_;
      if (envsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          envs_ = java.util.Collections.unmodifiableList(envs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.envs_ = envs_;
      } else {
        result.envs_ = envsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jetbrains.r.rinterop.ParentEnvsResponse) {
        return mergeFrom((org.jetbrains.r.rinterop.ParentEnvsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.r.rinterop.ParentEnvsResponse other) {
      if (other == org.jetbrains.r.rinterop.ParentEnvsResponse.getDefaultInstance()) return this;
      if (envsBuilder_ == null) {
        if (!other.envs_.isEmpty()) {
          if (envs_.isEmpty()) {
            envs_ = other.envs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEnvsIsMutable();
            envs_.addAll(other.envs_);
          }
          onChanged();
        }
      } else {
        if (!other.envs_.isEmpty()) {
          if (envsBuilder_.isEmpty()) {
            envsBuilder_.dispose();
            envsBuilder_ = null;
            envs_ = other.envs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            envsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEnvsFieldBuilder() : null;
          } else {
            envsBuilder_.addAllMessages(other.envs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.r.rinterop.ParentEnvsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.r.rinterop.ParentEnvsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo> envs_ =
      java.util.Collections.emptyList();
    private void ensureEnvsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        envs_ = new java.util.ArrayList<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo>(envs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder> envsBuilder_;

    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public java.util.List<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo> getEnvsList() {
      if (envsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(envs_);
      } else {
        return envsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public int getEnvsCount() {
      if (envsBuilder_ == null) {
        return envs_.size();
      } else {
        return envsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo getEnvs(int index) {
      if (envsBuilder_ == null) {
        return envs_.get(index);
      } else {
        return envsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder setEnvs(
        int index, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo value) {
      if (envsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvsIsMutable();
        envs_.set(index, value);
        onChanged();
      } else {
        envsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder setEnvs(
        int index, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder builderForValue) {
      if (envsBuilder_ == null) {
        ensureEnvsIsMutable();
        envs_.set(index, builderForValue.build());
        onChanged();
      } else {
        envsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder addEnvs(org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo value) {
      if (envsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvsIsMutable();
        envs_.add(value);
        onChanged();
      } else {
        envsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder addEnvs(
        int index, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo value) {
      if (envsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvsIsMutable();
        envs_.add(index, value);
        onChanged();
      } else {
        envsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder addEnvs(
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder builderForValue) {
      if (envsBuilder_ == null) {
        ensureEnvsIsMutable();
        envs_.add(builderForValue.build());
        onChanged();
      } else {
        envsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder addEnvs(
        int index, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder builderForValue) {
      if (envsBuilder_ == null) {
        ensureEnvsIsMutable();
        envs_.add(index, builderForValue.build());
        onChanged();
      } else {
        envsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder addAllEnvs(
        java.lang.Iterable<? extends org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo> values) {
      if (envsBuilder_ == null) {
        ensureEnvsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, envs_);
        onChanged();
      } else {
        envsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder clearEnvs() {
      if (envsBuilder_ == null) {
        envs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        envsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public Builder removeEnvs(int index) {
      if (envsBuilder_ == null) {
        ensureEnvsIsMutable();
        envs_.remove(index);
        onChanged();
      } else {
        envsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder getEnvsBuilder(
        int index) {
      return getEnvsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder getEnvsOrBuilder(
        int index) {
      if (envsBuilder_ == null) {
        return envs_.get(index);  } else {
        return envsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public java.util.List<? extends org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder> 
         getEnvsOrBuilderList() {
      if (envsBuilder_ != null) {
        return envsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(envs_);
      }
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder addEnvsBuilder() {
      return getEnvsFieldBuilder().addBuilder(
          org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder addEnvsBuilder(
        int index) {
      return getEnvsFieldBuilder().addBuilder(
          index, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .rplugininterop.ParentEnvsResponse.EnvInfo envs = 1;</code>
     */
    public java.util.List<org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder> 
         getEnvsBuilderList() {
      return getEnvsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder> 
        getEnvsFieldBuilder() {
      if (envsBuilder_ == null) {
        envsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfo.Builder, org.jetbrains.r.rinterop.ParentEnvsResponse.EnvInfoOrBuilder>(
                envs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        envs_ = null;
      }
      return envsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.ParentEnvsResponse)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.ParentEnvsResponse)
  private static final org.jetbrains.r.rinterop.ParentEnvsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jetbrains.r.rinterop.ParentEnvsResponse();
  }

  public static org.jetbrains.r.rinterop.ParentEnvsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParentEnvsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ParentEnvsResponse>() {
    @java.lang.Override
    public ParentEnvsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ParentEnvsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParentEnvsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParentEnvsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jetbrains.r.rinterop.ParentEnvsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

