// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface RepoRemovePackageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.RepoRemovePackageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string packageName = 1;</code>
   */
  java.lang.String getPackageName();
  /**
   * <code>string packageName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <code>string libraryPath = 2;</code>
   */
  java.lang.String getLibraryPath();
  /**
   * <code>string libraryPath = 2;</code>
   */
  com.google.protobuf.ByteString
      getLibraryPathBytes();
}
