// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

/**
 * Protobuf type {@code rplugininterop.SetValueRequest}
 */
public final class SetValueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rplugininterop.SetValueRequest)
    SetValueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetValueRequest.newBuilder() to construct.
  private SetValueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetValueRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetValueRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetValueRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.jetbrains.r.rinterop.RRef.Builder subBuilder = null;
            if (ref_ != null) {
              subBuilder = ref_.toBuilder();
            }
            ref_ = input.readMessage(org.jetbrains.r.rinterop.RRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ref_);
              ref_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.jetbrains.r.rinterop.RRef.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(org.jetbrains.r.rinterop.RRef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_SetValueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_SetValueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.r.rinterop.SetValueRequest.class, org.jetbrains.r.rinterop.SetValueRequest.Builder.class);
  }

  public static final int REF_FIELD_NUMBER = 1;
  private org.jetbrains.r.rinterop.RRef ref_;
  /**
   * <code>.rplugininterop.RRef ref = 1;</code>
   * @return Whether the ref field is set.
   */
  @java.lang.Override
  public boolean hasRef() {
    return ref_ != null;
  }
  /**
   * <code>.rplugininterop.RRef ref = 1;</code>
   * @return The ref.
   */
  @java.lang.Override
  public org.jetbrains.r.rinterop.RRef getRef() {
    return ref_ == null ? org.jetbrains.r.rinterop.RRef.getDefaultInstance() : ref_;
  }
  /**
   * <code>.rplugininterop.RRef ref = 1;</code>
   */
  @java.lang.Override
  public org.jetbrains.r.rinterop.RRefOrBuilder getRefOrBuilder() {
    return getRef();
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private org.jetbrains.r.rinterop.RRef value_;
  /**
   * <code>.rplugininterop.RRef value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.rplugininterop.RRef value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public org.jetbrains.r.rinterop.RRef getValue() {
    return value_ == null ? org.jetbrains.r.rinterop.RRef.getDefaultInstance() : value_;
  }
  /**
   * <code>.rplugininterop.RRef value = 2;</code>
   */
  @java.lang.Override
  public org.jetbrains.r.rinterop.RRefOrBuilder getValueOrBuilder() {
    return getValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ref_ != null) {
      output.writeMessage(1, getRef());
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ref_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRef());
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jetbrains.r.rinterop.SetValueRequest)) {
      return super.equals(obj);
    }
    org.jetbrains.r.rinterop.SetValueRequest other = (org.jetbrains.r.rinterop.SetValueRequest) obj;

    if (hasRef() != other.hasRef()) return false;
    if (hasRef()) {
      if (!getRef()
          .equals(other.getRef())) return false;
    }
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRef()) {
      hash = (37 * hash) + REF_FIELD_NUMBER;
      hash = (53 * hash) + getRef().hashCode();
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jetbrains.r.rinterop.SetValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jetbrains.r.rinterop.SetValueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rplugininterop.SetValueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rplugininterop.SetValueRequest)
      org.jetbrains.r.rinterop.SetValueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_SetValueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_SetValueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.r.rinterop.SetValueRequest.class, org.jetbrains.r.rinterop.SetValueRequest.Builder.class);
    }

    // Construct using org.jetbrains.r.rinterop.SetValueRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (refBuilder_ == null) {
        ref_ = null;
      } else {
        ref_ = null;
        refBuilder_ = null;
      }
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jetbrains.r.rinterop.Service.internal_static_rplugininterop_SetValueRequest_descriptor;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.SetValueRequest getDefaultInstanceForType() {
      return org.jetbrains.r.rinterop.SetValueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.SetValueRequest build() {
      org.jetbrains.r.rinterop.SetValueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jetbrains.r.rinterop.SetValueRequest buildPartial() {
      org.jetbrains.r.rinterop.SetValueRequest result = new org.jetbrains.r.rinterop.SetValueRequest(this);
      if (refBuilder_ == null) {
        result.ref_ = ref_;
      } else {
        result.ref_ = refBuilder_.build();
      }
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jetbrains.r.rinterop.SetValueRequest) {
        return mergeFrom((org.jetbrains.r.rinterop.SetValueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.r.rinterop.SetValueRequest other) {
      if (other == org.jetbrains.r.rinterop.SetValueRequest.getDefaultInstance()) return this;
      if (other.hasRef()) {
        mergeRef(other.getRef());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.r.rinterop.SetValueRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.r.rinterop.SetValueRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.jetbrains.r.rinterop.RRef ref_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder> refBuilder_;
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     * @return Whether the ref field is set.
     */
    public boolean hasRef() {
      return refBuilder_ != null || ref_ != null;
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     * @return The ref.
     */
    public org.jetbrains.r.rinterop.RRef getRef() {
      if (refBuilder_ == null) {
        return ref_ == null ? org.jetbrains.r.rinterop.RRef.getDefaultInstance() : ref_;
      } else {
        return refBuilder_.getMessage();
      }
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public Builder setRef(org.jetbrains.r.rinterop.RRef value) {
      if (refBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ref_ = value;
        onChanged();
      } else {
        refBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public Builder setRef(
        org.jetbrains.r.rinterop.RRef.Builder builderForValue) {
      if (refBuilder_ == null) {
        ref_ = builderForValue.build();
        onChanged();
      } else {
        refBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public Builder mergeRef(org.jetbrains.r.rinterop.RRef value) {
      if (refBuilder_ == null) {
        if (ref_ != null) {
          ref_ =
            org.jetbrains.r.rinterop.RRef.newBuilder(ref_).mergeFrom(value).buildPartial();
        } else {
          ref_ = value;
        }
        onChanged();
      } else {
        refBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public Builder clearRef() {
      if (refBuilder_ == null) {
        ref_ = null;
        onChanged();
      } else {
        ref_ = null;
        refBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public org.jetbrains.r.rinterop.RRef.Builder getRefBuilder() {
      
      onChanged();
      return getRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    public org.jetbrains.r.rinterop.RRefOrBuilder getRefOrBuilder() {
      if (refBuilder_ != null) {
        return refBuilder_.getMessageOrBuilder();
      } else {
        return ref_ == null ?
            org.jetbrains.r.rinterop.RRef.getDefaultInstance() : ref_;
      }
    }
    /**
     * <code>.rplugininterop.RRef ref = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder> 
        getRefFieldBuilder() {
      if (refBuilder_ == null) {
        refBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder>(
                getRef(),
                getParentForChildren(),
                isClean());
        ref_ = null;
      }
      return refBuilder_;
    }

    private org.jetbrains.r.rinterop.RRef value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder> valueBuilder_;
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     * @return The value.
     */
    public org.jetbrains.r.rinterop.RRef getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? org.jetbrains.r.rinterop.RRef.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public Builder setValue(org.jetbrains.r.rinterop.RRef value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public Builder setValue(
        org.jetbrains.r.rinterop.RRef.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public Builder mergeValue(org.jetbrains.r.rinterop.RRef value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            org.jetbrains.r.rinterop.RRef.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public org.jetbrains.r.rinterop.RRef.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    public org.jetbrains.r.rinterop.RRefOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            org.jetbrains.r.rinterop.RRef.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.rplugininterop.RRef value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.jetbrains.r.rinterop.RRef, org.jetbrains.r.rinterop.RRef.Builder, org.jetbrains.r.rinterop.RRefOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rplugininterop.SetValueRequest)
  }

  // @@protoc_insertion_point(class_scope:rplugininterop.SetValueRequest)
  private static final org.jetbrains.r.rinterop.SetValueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jetbrains.r.rinterop.SetValueRequest();
  }

  public static org.jetbrains.r.rinterop.SetValueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetValueRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetValueRequest>() {
    @java.lang.Override
    public SetValueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetValueRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetValueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetValueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jetbrains.r.rinterop.SetValueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

