// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface StackFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.StackFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   * @return The position.
   */
  org.jetbrains.r.rinterop.SourcePosition getPosition();
  /**
   * <code>.rplugininterop.SourcePosition position = 1;</code>
   */
  org.jetbrains.r.rinterop.SourcePositionOrBuilder getPositionOrBuilder();

  /**
   * <code>string functionName = 2;</code>
   * @return The functionName.
   */
  java.lang.String getFunctionName();
  /**
   * <code>string functionName = 2;</code>
   * @return The bytes for functionName.
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();

  /**
   * <code>int64 equalityObject = 3;</code>
   * @return The equalityObject.
   */
  long getEqualityObject();

  /**
   * <code>.rplugininterop.ExtendedSourcePosition extendedSourcePosition = 4;</code>
   * @return Whether the extendedSourcePosition field is set.
   */
  boolean hasExtendedSourcePosition();
  /**
   * <code>.rplugininterop.ExtendedSourcePosition extendedSourcePosition = 4;</code>
   * @return The extendedSourcePosition.
   */
  org.jetbrains.r.rinterop.ExtendedSourcePosition getExtendedSourcePosition();
  /**
   * <code>.rplugininterop.ExtendedSourcePosition extendedSourcePosition = 4;</code>
   */
  org.jetbrains.r.rinterop.ExtendedSourcePositionOrBuilder getExtendedSourcePositionOrBuilder();

  /**
   * <code>string sourcePositionText = 5;</code>
   * @return The sourcePositionText.
   */
  java.lang.String getSourcePositionText();
  /**
   * <code>string sourcePositionText = 5;</code>
   * @return The bytes for sourcePositionText.
   */
  com.google.protobuf.ByteString
      getSourcePositionTextBytes();
}
