// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.jetbrains.r.rinterop;

public interface TextFigureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rplugininterop.TextFigure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.rplugininterop.AffinePoint position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.rplugininterop.AffinePoint position = 2;</code>
   * @return The position.
   */
  org.jetbrains.r.rinterop.AffinePoint getPosition();
  /**
   * <code>.rplugininterop.AffinePoint position = 2;</code>
   */
  org.jetbrains.r.rinterop.AffinePointOrBuilder getPositionOrBuilder();

  /**
   * <code>float angle = 3;</code>
   * @return The angle.
   */
  float getAngle();

  /**
   * <code>float anchor = 4;</code>
   * @return The anchor.
   */
  float getAnchor();

  /**
   * <code>int32 fontIndex = 5;</code>
   * @return The fontIndex.
   */
  int getFontIndex();

  /**
   * <code>int32 colorIndex = 6;</code>
   * @return The colorIndex.
   */
  int getColorIndex();
}
